### ISSUE TITLE
Plugin Not Parsing When Starting Server

### ISSUE THREAD

**Issue by deryckdx** [shoghicp/WorldEditor#1]
For some reason, when I start my server I get this error that it's not parsing correctly, or something along those lines. I've attached a picture below, so you know what I'm talking about.
![IMG_0406](https://f.cloud.github.com/assets/4122872/410249/02e1b6d0-ab69-11e2-9ee4-03236c96bcea.jpg)

**Comment by shoghicp** [comment]
You may have corrupted the WorldEditor.php. Test downloading it using https://github.com/shoghicp/WorldEditor/archive/master.zip, and then moving the WorldEditor.php from there into the plugins folder (overwriting the old one)

**Comment by deryckdx** [comment]
Ok, I'll try it when I can and let you know. Thank you for all you do!

**Comment by deryckdx** [comment]
It installed and started correctly, no more red parsing error, but I can't use it in game. Is it compatible with the latest Dev build?

**Comment by shoghicp** [comment]
You've to use it with SignConsole, or use it with "sudo" in console
