### ISSUE TITLE
Using Wand or //Set Clears Inventory on 0.7.0.

### ISSUE THREAD

**Issue by deryckdx** [shoghicp/WorldEditor#3]
You probably already know this, but just in case I thought I would report it.

**Comment by shoghicp** [comment]
It only clears your hotbar. It is a PocketMine-MP issue that I'm trying to fix

**Comment by deryckdx** [comment]
If it's not fixed yet, why did you close it?

**Comment by shoghicp** [comment]
Because it has nothing to do with WorldEditor. It is a PocketMine issue.

**Comment by deryckdx** [comment]
Oh I see. Thanks, I was just a little confused.
